/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.translateapp.translateapp.frontend;

/**
 *
 * @author dorjanzenjelaj
 */
public class AnswerSecurityQuestionsGUI extends javax.swing.JPanel {

    /**
     * Creates new form loginInterface
     */
    public AnswerSecurityQuestionsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabe1 = new javax.swing.JLabel();
        logoLabel2 = new javax.swing.JLabel();
        sendButton = new java.awt.Button();
        securityAnswer1 = new java.awt.TextField();
        answerLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        securityQuestion1 = new javax.swing.JLabel();
        securityAnswer3 = new java.awt.TextField();
        securityQuestion3 = new javax.swing.JLabel();
        answerLabel2 = new javax.swing.JLabel();
        securityAnswer2 = new java.awt.TextField();
        securityQuestion2 = new javax.swing.JLabel();
        answerLabel3 = new javax.swing.JLabel();
        backButton = new java.awt.Button();
        messageLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(new java.awt.Color(51, 51, 51));
        setToolTipText("");

        logoLabe1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        logoLabe1.setForeground(new java.awt.Color(255, 255, 255));
        logoLabe1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        logoLabe1.setText("Lang");
        logoLabe1.setIconTextGap(0);

        logoLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        logoLabel2.setForeground(new java.awt.Color(1, 111, 160));
        logoLabel2.setText("Learner");
        logoLabel2.setIconTextGap(0);

        sendButton.setBackground(new java.awt.Color(1, 111, 160));
        sendButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setLabel("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        securityAnswer1.setBackground(new java.awt.Color(153, 153, 153));
        securityAnswer1.setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        securityAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnswer1ActionPerformed(evt);
            }
        });

        answerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        answerLabel1.setText("Enter answer 1");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        securityQuestion1.setForeground(new java.awt.Color(255, 255, 255));
        securityQuestion1.setText("What was your first car?");

        securityAnswer3.setBackground(new java.awt.Color(153, 153, 153));
        securityAnswer3.setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        securityAnswer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnswer3ActionPerformed(evt);
            }
        });

        securityQuestion3.setForeground(new java.awt.Color(255, 255, 255));
        securityQuestion3.setText("What was your childhood pet name?");

        answerLabel2.setForeground(new java.awt.Color(255, 255, 255));
        answerLabel2.setText("Enter answer 2");

        securityAnswer2.setBackground(new java.awt.Color(153, 153, 153));
        securityAnswer2.setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        securityAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnswer2ActionPerformed(evt);
            }
        });

        securityQuestion2.setForeground(new java.awt.Color(255, 255, 255));
        securityQuestion2.setText("What is your mothers maiden name?");

        answerLabel3.setForeground(new java.awt.Color(255, 255, 255));
        answerLabel3.setText("Enter answer 3");

        backButton.setBackground(new java.awt.Color(1, 111, 160));
        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setLabel("<-");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        messageLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageLabel.setText("Please provide answres to my problems");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(logoLabe1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(securityQuestion3, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(securityAnswer3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(securityAnswer1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(answerLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(answerLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(answerLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(securityQuestion1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(securityQuestion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(securityAnswer2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoLabe1)
                    .addComponent(logoLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(securityQuestion1)
                .addGap(18, 18, 18)
                .addComponent(answerLabel1)
                .addGap(2, 2, 2)
                .addComponent(securityAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityQuestion2)
                .addGap(15, 15, 15)
                .addComponent(answerLabel2)
                .addGap(1, 1, 1)
                .addComponent(securityAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(securityQuestion3)
                .addGap(18, 18, 18)
                .addComponent(answerLabel3)
                .addGap(1, 1, 1)
                .addComponent(securityAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(messageLabel)
                .addGap(47, 47, 47)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        answerLabel1.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void securityAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnswer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityAnswer1ActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonActionPerformed

    private void securityAnswer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnswer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityAnswer3ActionPerformed

    private void securityAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnswer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityAnswer2ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel1;
    private javax.swing.JLabel answerLabel2;
    private javax.swing.JLabel answerLabel3;
    private java.awt.Button backButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logoLabe1;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JLabel messageLabel;
    private java.awt.TextField securityAnswer1;
    private java.awt.TextField securityAnswer2;
    private java.awt.TextField securityAnswer3;
    private javax.swing.JLabel securityQuestion1;
    private javax.swing.JLabel securityQuestion2;
    private javax.swing.JLabel securityQuestion3;
    private java.awt.Button sendButton;
    // End of variables declaration//GEN-END:variables
}
